# Adjust according to your needs
name: Release RC

on:
    issue_comment:
        types:
            - created

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    get-branch:
        if: ${{ github.event.issue.pull_request && (github.event.comment.body == 'rc-publish' || github.event.comment.body == '/rc-publish')}}
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.get_branch.outputs.branch }}
        steps:
            - name: Get PR branch name
              id: get_branch
              run: |
                  PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
                  echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"

    rc:
        needs: get-branch
        uses: ./.github/workflows/publish.yaml
        with:
            publish_type: rc
            npm_tag: rc
            ref: ${{ needs.get-branch.outputs.branch }}
            version_template: '{VERSION}-rc.{DATE}-{COMMITID7}'
            packages_dir: '.'
            excludes: '.turbo,.github'
            create_release: true
        secrets:
            action_token: ${{ secrets.ACTION_TOKEN }}
